testSimple_threadpool_object.o: testSimple_threadpool_object.cpp \
 ../src-SQ_c++11/SimpleObjThreadPool.h \
 ../src-SQ_c++11/./ThreadSafeQueue.h \
 ../src-SQ_c++11/../src/CriticalStorage.h ../../PsimagLite/src/Vector.h \
 ../../PsimagLite/src/Complex.h ../../PsimagLite/src/AllocatorCpu.h \
 ../../PsimagLite/src/String.h ../src-SQ_c++11/../src/Mpi.h \
 ../src-SQ_c++11/../src/ParallelTypeEnum.h \
 ../src-SQ_c++11/../src/CriticalStorageImpl.h \
 ../src-SQ_c++11/../src/CriticalReal.h \
 ../src-SQ_c++11/../src/ConcurrentPattern.h ../src-SQ/CriticalStorage.h
